---
- name: Generate Runner values
  template:
    src: runner-values.yaml.j2
    dest: /tmp/gitlab-runner-values.yaml

- name: Install GitLab Runner
  kubernetes.core.helm:
    name: gitlab-runner
    chart_ref: gitlab/gitlab-runner
    chart_version: "{{ gitlab_runner_chart_version }}"
    release_namespace: "{{ gitlab_namespace }}"
    values_files:
      - /tmp/gitlab-runner-values.yaml
    wait: true

- name: Wait for Runner pods
  command: >
    kubectl wait --for=condition=ready pod 
    -l app=gitlab-runner 
    -n {{ gitlab_namespace }} 
    --timeout=300s