---
gitlab_hostname: "gitlab.local"
install_gitlab_runner: true

# GitLab
gitlab_url: "http://192.168.2.6"
gitlab_external_url: "93.77.178.234:84"

# Project
project_name: "nginx_index_file"
project_visibility: "public"
setup_cicd: true

# Kubernetes
kube_namespace: "nginx-app"
kubeconfig_path: "~/.kube/config"

# GitHub
github_owner: "StudentIrgups"
github_repo: "nginx_index_file"